app/routes/main.py
from flask import Blueprint, render_template, Response
from flask import redirect, url_for
from flask_login import current_user
main = Blueprint('main', __name__)

@main.route('/')
def home() -> Response:
    """Exibe a página inicial ou o painel do usuário logado."""

    # se o usuário estiver logado, redireciona para a página de tickets
    if current_user.is_authenticated:
        return redirect(url_for('dashboard.user_tickets'))
    # caso contrário, renderiza a página de login
    return redirect(url_for('auth.login'))

app/templates/profile/change-password.html
{% extends "layout.html" %}

{% block content %}
<form method="POST" action="#" class="w-full lg:w-1/4 mx-auto bg-white dark:bg-gray-800 p-8 rounded-lg shadow-md">
    <fieldset class="space-y-6">
        <legend class="text-2xl font-bold border-b pb-2 mb-4 dark:text-white"> Alterar senha </legend>

        <!-- senha anterior -->
        <div x-data="{ isPasswordVisible: false }">

            <label for="old_password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"> Senha
                anterior </label>

            <div class="relative">
                <input :type="isPasswordVisible ? 'text' : 'password'" name="old_password" id="old_password"
                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-2.5 pr-12 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white"
                    required>

                <div class="absolute inset-y-0 right-0 pr-3 flex items-center text-sm leading-5">
                    <button @click="isPasswordVisible = !isPasswordVisible" type="button" title="Mostrar/Ocultar senha"
                        class="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200">
                        <svg x-show="!isPasswordVisible" class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                        </svg>
                        <svg x-show="isPasswordVisible" class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M3.98 8.223A10.477 10.477 0 001.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.45 10.45 0 0112 4.5c4.756 0 8.773 3.162 10.065 7.498a10.523 10.523 0 01-4.293 5.774M6.228 6.228L3 3m3.228 3.228l3.65 3.65m7.894 7.894L21 21m-3.228-3.228l-3.65-3.65m0 0a3 3 0 10-4.243-4.243m4.243 4.243l-4.243-4.243" />
                        </svg>
                    </button>
                </div>
            </div>
        </div>

        <!-- nova senha -->
        <div x-data="{ 
                                    password: '', 
                                    isPasswordVisible: false,
                                    generatePassword() {
                                        const length = 16;
                                        const charset = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+~`|}{[]:;?><,./-=';
                                        let newPassword = '';
                                        for (let i = 0, n = charset.length; i < length; ++i) {
                                            newPassword += charset.charAt(Math.floor(Math.random() * n));
                                        }
                                        this.password = newPassword;
                                        this.isPasswordVisible = true; // Mostra a senha gerada
                                    }
                                }">

            <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"> Digite uma nova
                senha </label>

            <div class="relative">
                <input :type="isPasswordVisible ? 'text' : 'password'" name="password" id="password" x-model="password"
                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-2.5 pr-20 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white"
                    required>

                <div class="absolute inset-y-0 right-0 pr-3 flex items-center space-x-2 text-sm leading-5">
                    <!-- botão para gerar senha -->
                    <button @click="generatePassword" type="button" title="Gerar senha aleatória"
                        class="text-purple-600 hover:text-purple-800 dark:text-purple-400 dark:hover:text-purple-300">
                        <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                            stroke-width="1.5" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M15.75 5.25a3 3 0 013 3m3 0a6 6 0 01-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1121.75 8.25z" />
                        </svg>
                    </button>
                    <!-- botão mostrar/ocultar senha -->
                    <button @click="isPasswordVisible = !isPasswordVisible" type="button" title="Mostrar/Ocultar senha"
                        class="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200">
                        <svg x-show="!isPasswordVisible" class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                        </svg>
                        <svg x-show="isPasswordVisible" class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M3.98 8.223A10.477 10.477 0 001.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.45 10.45 0 0112 4.5c4.756 0 8.773 3.162 10.065 7.498a10.523 10.523 0 01-4.293 5.774M6.228 6.228L3 3m3.228 3.228l3.65 3.65m7.894 7.894L21 21m-3.228-3.228l-3.65-3.65m0 0a3 3 0 10-4.243-4.243m4.243 4.243l-4.243-4.243" />
                        </svg>
                    </button>
                </div>
            </div>
        </div>

        <!-- confirmar nova senha -->
        <div x-data="{ isPasswordVisible: false }">

            <label for="confirm_password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"> Confirme
                a nova senha </label>

            <div class="relative">
                <input :type="isPasswordVisible ? 'text' : 'password'" name="confirm_password" id="confirm_password"
                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-2.5 pr-12 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white"
                    required>

                <div class="absolute inset-y-0 right-0 pr-3 flex items-center text-sm leading-5">
                    <button @click="isPasswordVisible = !isPasswordVisible" type="button" title="Mostrar/Ocultar senha"
                        class="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200">
                        <svg x-show="!isPasswordVisible" class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                        </svg>
                        <svg x-show="isPasswordVisible" class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M3.98 8.223A10.477 10.477 0 001.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.45 10.45 0 0112 4.5c4.756 0 8.773 3.162 10.065 7.498a10.523 10.523 0 01-4.293 5.774M6.228 6.228L3 3m3.228 3.228l3.65 3.65m7.894 7.894L21 21m-3.228-3.228l-3.65-3.65m0 0a3 3 0 10-4.243-4.243m4.243 4.243l-4.243-4.243" />
                        </svg>
                    </button>
                </div>
            </div>
        </div>
    </fieldset>
    <!-- voltar -->
        <div class="mt-6">
            <button type="submit"
                class="w-full flex justify-center items-center text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-800 disabled:opacity-50 disabled:cursor-not-allowed">
                Alterar senha </button>
            <a href="{{ url_for('profile.view') }}" class="mt-4 w-full flex justify-center items-center px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg shadow-sm text-sm font-medium
                        text-gray-700 bg-white hover:bg-gray-50 
                        dark:text-gray-200 dark:bg-gray-800 dark:hover:bg-gray-600 
                        transition-colors duration-200"> Voltar
            </a>
        </div>
</form>
{% endblock %}

app/templates/profile/main.html
{% extends "layout.html" %}

{% block content %}
<div class="w-full lg:w-1/6 mx-auto bg-white dark:bg-gray-800 p-8 rounded-lg shadow-md">
    <fieldset class="space-y-6">
        <legend class="text-2xl font-bold border-b pb-2 mb-4 dark:text-white"> Meu perfil </legend>

        <div class="mt-4">
            <a href="{{ url_for('profile.change_password') }}"
                class="w-1/2 mx-auto flex justify-center items-center text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-800 disabled:opacity-50 disabled:cursor-not-allowed">
                Alterar senha </a>
        </div>

        <div class="mt-4">
            <a href="{{ url_for('main.home') }}" class="w-1/2 flex justify-center items-center mx-auto px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg shadow-sm text-sm font-medium 
                        text-gray-700 bg-white hover:bg-gray-50 
                        dark:text-gray-200 dark:bg-gray-800 dark:hover:bg-gray-600 
                        transition-colors duration-200"> Voltar
            </a>
        </div>

    </fieldset>
</div>
{% endblock %}